source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "jbuilder"
gem "redis", "~> 5.0"
gem "connection_pool", "< 3"
gem "sidekiq"
gem "jwt"
gem "bcrypt"
gem "pundit"
gem "karafka", ">= 2.2"
gem "rack-cors"
gem "bootsnap", require: false

group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "pry-rails"
  gem "pry-byebug"
  gem "rubocop-rails", require: false
  gem "rubocop-rspec", require: false
end

group :test do
  gem "shoulda-matchers"
  gem "database_cleaner-active_record"
  gem "simplecov", require: false
end
